{{--
    ⚠ DRAFT — REQUIRES LEGAL REVIEW BEFORE LAUNCH.
    India's Digital Personal Data Protection Act 2023 imposes specific
    obligations (consent, notice, grievance officer, breach reporting). This
    draft is written to be honest about what the platform actually collects,
    but placeholders in [SQUARE BRACKETS] must be completed and a qualified
    lawyer must review it before it is published as a binding policy.
--}}
@extends('layouts.site')

@section('title', 'Privacy Policy — The Real Bingo')
@section('meta_description', 'How The Real Bingo collects, uses and protects your personal data.')

@section('content')
<div class="wrap doc">
    <h1>Privacy Policy</h1>
    <p class="updated">Last updated: {{ date('d F Y') }}</p>

    <div class="notice" style="margin-bottom:2rem;">
        This policy explains what personal data we collect, why we collect it, and what rights you have over it.
    </div>

    <h2>1. Who is responsible for your data</h2>
    <p>[COMPANY LEGAL NAME], [REGISTERED ADDRESS], is responsible for the personal data described here. For any privacy question or request, contact [PRIVACY / GRIEVANCE OFFICER NAME] at [PRIVACY EMAIL].</p>

    <h2>2. What we collect</h2>
    <p><strong>Information you give us</strong></p>
    <ul>
        <li>Mobile number, and email address if you provide one</li>
        <li>Name, gender, date of birth and address</li>
        <li>KYC documents and identifiers — Aadhaar number, PAN number, and the document images you upload</li>
        <li>Bank account or UPI details used for withdrawals</li>
        <li>Profile photograph, if you choose to upload one</li>
    </ul>

    <p style="margin-top:1rem;"><strong>Information generated by using the platform</strong></p>
    <ul>
        <li>Wallet balance and a permanent record of every transaction — deposits, withdrawals, bets, payouts and transfers</li>
        <li>Bets placed and rounds played</li>
        <li>Referral code, and the link between an inviting player and those they invited</li>
        <li>Login and session records, including access tokens issued to your devices</li>
        <li>Technical information such as device type and app version</li>
    </ul>

    <h2>3. Why we use it</h2>
    <ul>
        <li><strong>To run your account and the game</strong> — registration, login, placing bets, settling rounds, maintaining your balance.</li>
        <li><strong>To verify your identity</strong> — KYC checks are required before withdrawals and help prevent fraud and underage play.</li>
        <li><strong>To process money</strong> — crediting deposits, processing withdrawals to your verified bank or UPI details, and paying referral bonuses.</li>
        <li><strong>To keep the platform safe</strong> — detecting fraud, collusion, multiple accounts and other breaches of our terms.</li>
        <li><strong>To meet legal obligations</strong> — including record-keeping and anti-money-laundering requirements.</li>
        <li><strong>To support you</strong> — responding to questions and resolving disputes.</li>
    </ul>

    <h2>4. Who we share it with</h2>
    <p>We do not sell your personal data. We share it only where necessary:</p>
    <ul>
        <li><strong>Payment and banking providers</strong>, to process deposits and withdrawals</li>
        <li><strong>SMS providers</strong>, to deliver one-time passwords</li>
        <li><strong>Hosting and infrastructure providers</strong>, who store data on our behalf</li>
        <li><strong>Regulators, law enforcement or courts</strong>, where we are legally required to disclose</li>
        <li><strong>Professional advisers</strong>, such as auditors or lawyers, where necessary</li>
    </ul>

    <h2>5. How we protect it</h2>
    <ul>
        <li>All traffic between the app and our servers is encrypted in transit (HTTPS/TLS).</li>
        <li>Passwords are stored hashed, never in readable form. One-time passwords are also stored hashed.</li>
        <li>Access to administrative systems is restricted to authorised staff, with role-based permissions.</li>
        <li>Every movement of money is written to an immutable ledger, so financial records cannot be silently altered.</li>
    </ul>
    <p>No system can be guaranteed completely secure, but we take these measures seriously and review them.</p>

    <h2>6. How long we keep it</h2>
    <p>We keep your account and transaction data for as long as your account is open, and afterwards for as long as we are required to for legal, tax, audit and anti-money-laundering purposes. Financial and KYC records are typically retained for [RETENTION PERIOD] after account closure. Data no longer needed is deleted or anonymised.</p>

    <h2>7. Your rights</h2>
    <p>Subject to applicable law, you may:</p>
    <ul>
        <li>Request a copy of the personal data we hold about you</li>
        <li>Ask us to correct data that is wrong or incomplete</li>
        <li>Ask us to delete your data, where we are not required to keep it</li>
        <li>Withdraw consent where our use of your data relies on it</li>
        <li>Raise a complaint about how your data is handled</li>
    </ul>
    <p>To exercise any of these, contact [PRIVACY EMAIL]. We may need to verify your identity first. Note that some data — particularly financial and KYC records — must be retained even after account closure, so a deletion request may not remove everything.</p>

    <h2>8. Children</h2>
    <p>The platform is strictly for adults aged 18 and over. We do not knowingly collect data from anyone under 18. If we discover an account belongs to a minor, it will be closed. If you believe a minor has registered, contact us at [PRIVACY EMAIL].</p>

    <h2>9. Changes to this policy</h2>
    <p>We may update this policy. Material changes will be notified in the app or on this page, and the "last updated" date will change.</p>

    <h2>10. Contact and complaints</h2>
    <p>Privacy questions, requests and complaints: [PRIVACY / GRIEVANCE OFFICER NAME], [PRIVACY EMAIL], [REGISTERED ADDRESS]. If you are not satisfied with our response, you may escalate to the relevant data protection authority.</p>
</div>
@endsection
